In [ ]:
import pandas as pd
import xlrd
import time
## This function saves the pickled dataframe minute by minute. Dummy.pkl is the roving data file
## Meaning it's constantly being updated and compared to the static.
url = 'https://www.bchydro.com/bctc/system_cms/outages/forced/Annual_Plan_Extract.xls'
df = pd.read_excel(url,index_col=False)
date_LastUpdate=df.iloc[0:1,0:1]

In [27]:
df.columns = df.iloc[0]

In [40]:
date_LastUpdate

  Annual Plan Extract (11/27/2018 9:30:03 AM)
0                                    Outage #

In [29]:
df1=df.iloc[1:]
df = df1

In [30]:
df1

,Outage #,Outage Status,AP Outage Title,Outage Purpose,Requested Equipment,Start Date\n(MM/DD/YYYY HH:MM:SS),Complete Date\n(MM/DD/YYYY HH:MM:SS),Outage Type : Continuous /Daily,Path 3 (N->S) ING to CUS\n(MW),Path 3 (N->S) BC to US\n(MW),Path 3 (S->N)CUS to ING\n(MW),Path 3 (S->N) US to BC\n(MW),Path 1 BC AB (W->E) BC to AB\n(MW),Path 1 (E->W) AB to BC\n(MW),Resource Impact,NaN,Load Impact,Revision Date\n(MM/DD/YYYY HH:MM:SS)
1,8-00253033,Implemented,BSY G2,Synchronous Condensor Forced OOS,BSY G2,2016-08-26 00:43:00,2021-03-31 21:00:00,Continuous,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,N,2018-11-14 08:14:56.167000
2,8-00272608,Completed,MDN 2RX2 OOS,Forced Outage,MDN 2RX2,2017-02-02 16:12:05,2018-02-01 15:55:39,Continuous,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,N,2018-02-01 16:12:04.810000
3,8-00283784,Completed,HVDC Pole 2 OOS,For Operational Plan performance testing,HVDC POLE 2,2017-07-31 08:00:00,2018-07-26 05:23:06,Continuous,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,N,2018-07-26 05:33:10.787000
4,8-00310512,Completed,DMR SVC,Forced Outage,"DMR T8, DMR TSR3, DMR SVC",2017-12-04 11:03:53,2018-01-15 15:20:34,Continuous,2000,2400,NaN,NaN,NaN,NaN,N,NaN,N,2018-02-23 16:47:11.047000
5,8-00312015,Completed,KLY 5RX5 OOS,Forced OOS: Failed 5CB35,"KLY 5CB35, KLY 5DCB35, KLY 5RX5",2017-12-14 16:18:08,2018-03-20 11:29:22,Continuous,2000,2400,NaN,NaN,NaN,NaN,N,NaN,N,2018-03-20 13:50:40.160000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
740,8-00325112,Submitted,2L12 OOS,Breaker and CVT Inspections,"CKY 2CB20, CKY 2CB9, 2L12",2019-03-04 07:00:00,2019-03-08 18:00:00,Continuous,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,N,2018-10-31 09:31:35.093000
741,8-00314980,Proposed,INV T1 OOS,Transformer PCB Bushing replacement,INV T1,2019-03-04 08:00:00,2019-04-19 16:00:00,Continuous,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,N,2018-03-15 13:38:10.283000
742,8-00316610,Submitted,"GMS 5B7, 5B8, and 5B9 OOS",Black Start Tests,"GMS 5B7, GMS 5B9, GMS 5B8",2019-03-16 08:00:00,2019-03-16 20:00:00,Continuous,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,N,2018-02-19 11:33:53.310000
743,8-00234842,Submitted,BSY G4 OOS,Inspection,BSY G4,2019-03-18 07:00:00,2019-03-22 18:00:00,Continuous,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,Y,2018-11-21 13:22:23.093000
744,8-00234841,Proposed,BSY G1 OOS,Inspection,BSY G1,2019-03-25 07:00:00,2019-03-29 18:00:00,Continuous,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,Y,2018-11-21 13:33:03.077000

In [31]:
df = df.dropna(axis=1,how = 'all')
df666=date_LastUpdate.to_string()
df666 = df666[df666.find("(")+1:df666.find(")")]
column_names = ["x",'Outage #','Outage Status','AP Outage Title','Outage Purpose','Requested Equipment','Start Date','Complete Date','Recall Time','Outage Type','Path 3 N->S ING - CUS','Path 3 N->S BC - US','Path 3 S -> N CUS ING','Path 3 S -> N US - BC','Path 1 W -> E BC - AB','Path 1 E -> W AB - BC','Resource Impact','Load Impact','Posted to Plan','Under Review AOP','Revision Date']

In [32]:
keywords = ["Completed"]

In [33]:
df.columns.values[0:25]

array(['Outage #', 'Outage Status', 'AP Outage Title', 'Outage Purpose',
       'Requested Equipment', 'Start Date\n(MM/DD/YYYY HH:MM:SS)',
       'Complete Date\n(MM/DD/YYYY HH:MM:SS)',
       'Outage Type : Continuous /Daily',
       'Path 3 (N->S) ING to CUS\n(MW)', 'Path 3 (N->S) BC to US\n(MW)',
       'Path 3 (S->N)CUS to ING\n(MW)', 'Path 3 (S->N) US to BC\n(MW)',
       'Path 1 BC AB (W->E) BC to AB\n(MW)',
       'Path 1 (E->W) AB to BC\n(MW)', 'Resource Impact', 'Load Impact',
       'Revision Date\n(MM/DD/YYYY HH:MM:SS)'], dtype=object)

In [34]:
df1

,Outage #,Outage Status,AP Outage Title,Outage Purpose,Requested Equipment,Start Date\n(MM/DD/YYYY HH:MM:SS),Complete Date\n(MM/DD/YYYY HH:MM:SS),Outage Type : Continuous /Daily,Path 3 (N->S) ING to CUS\n(MW),Path 3 (N->S) BC to US\n(MW),Path 3 (S->N)CUS to ING\n(MW),Path 3 (S->N) US to BC\n(MW),Path 1 BC AB (W->E) BC to AB\n(MW),Path 1 (E->W) AB to BC\n(MW),Resource Impact,NaN,Load Impact,Revision Date\n(MM/DD/YYYY HH:MM:SS)
1,8-00253033,Implemented,BSY G2,Synchronous Condensor Forced OOS,BSY G2,2016-08-26 00:43:00,2021-03-31 21:00:00,Continuous,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,N,2018-11-14 08:14:56.167000
2,8-00272608,Completed,MDN 2RX2 OOS,Forced Outage,MDN 2RX2,2017-02-02 16:12:05,2018-02-01 15:55:39,Continuous,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,N,2018-02-01 16:12:04.810000
3,8-00283784,Completed,HVDC Pole 2 OOS,For Operational Plan performance testing,HVDC POLE 2,2017-07-31 08:00:00,2018-07-26 05:23:06,Continuous,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,N,2018-07-26 05:33:10.787000
4,8-00310512,Completed,DMR SVC,Forced Outage,"DMR T8, DMR TSR3, DMR SVC",2017-12-04 11:03:53,2018-01-15 15:20:34,Continuous,2000,2400,NaN,NaN,NaN,NaN,N,NaN,N,2018-02-23 16:47:11.047000
5,8-00312015,Completed,KLY 5RX5 OOS,Forced OOS: Failed 5CB35,"KLY 5CB35, KLY 5DCB35, KLY 5RX5",2017-12-14 16:18:08,2018-03-20 11:29:22,Continuous,2000,2400,NaN,NaN,NaN,NaN,N,NaN,N,2018-03-20 13:50:40.160000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
740,8-00325112,Submitted,2L12 OOS,Breaker and CVT Inspections,"CKY 2CB20, CKY 2CB9, 2L12",2019-03-04 07:00:00,2019-03-08 18:00:00,Continuous,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,N,2018-10-31 09:31:35.093000
741,8-00314980,Proposed,INV T1 OOS,Transformer PCB Bushing replacement,INV T1,2019-03-04 08:00:00,2019-04-19 16:00:00,Continuous,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,N,2018-03-15 13:38:10.283000
742,8-00316610,Submitted,"GMS 5B7, 5B8, and 5B9 OOS",Black Start Tests,"GMS 5B7, GMS 5B9, GMS 5B8",2019-03-16 08:00:00,2019-03-16 20:00:00,Continuous,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,N,2018-02-19 11:33:53.310000
743,8-00234842,Submitted,BSY G4 OOS,Inspection,BSY G4,2019-03-18 07:00:00,2019-03-22 18:00:00,Continuous,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,Y,2018-11-21 13:22:23.093000
744,8-00234841,Proposed,BSY G1 OOS,Inspection,BSY G1,2019-03-25 07:00:00,2019-03-29 18:00:00,Continuous,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,Y,2018-11-21 13:33:03.077000

In [38]:
df.columns.values[0:20] = column_names[0:17]

In [39]:
print(df)

0             x     Outage #                Outage Status  \
1    8-00253033  Implemented                       BSY G2
8    8-00313250    Cancelled  KIT Rectifier Bay 11 outage
9    8-00313249     Approved  KIT Rectifier Bay 13 Outage
11   8-00308636     Proposed                     1L37 OOS
15   8-00265054    Cancelled   1L274 out from 1D2L274-EFT
..          ...          ...                          ...
740  8-00325112    Submitted                     2L12 OOS
741  8-00314980     Proposed                   INV T1 OOS
742  8-00316610    Submitted    GMS 5B7, 5B8, and 5B9 OOS
743  8-00234842    Submitted                   BSY G4 OOS
744  8-00234841     Proposed                   BSY G1 OOS

0                                  AP Outage Title             Outage Purpose  \
1                 Synchronous Condensor Forced OOS                     BSY G2
8                                      ice problem           KIT 4121-TXP-011
9                                      ice problem           KIT 4121-TXP-013
11                                  IPP connection                       1L37
15   Rating Restoration and Structure Replacement                1L274 / 887L
..                                             ...                        ...
740                    Breaker and CVT Inspections  CKY 2CB20, CKY 2CB9, 2L12
741          Transformer PCB Bushing replacement                       INV T1
742                              Black Start Tests  GMS 5B7, GMS 5B9, GMS 5B8
743                                     Inspection                     BSY G4
744                                     Inspection                     BSY G1

0    Requested Equipment           Start Date Complete Date Recall Time  \
1    2016-08-26 00:43:00  2021-03-31 21:00:00    Continuous         NaN
8    2018-01-05 07:00:00  2018-01-05 14:00:00    Continuous         NaN
9    2018-01-10 07:00:00  2018-01-10 15:00:00    Continuous         NaN
11   2018-01-15 08:00:00  2018-01-29 16:00:00    Continuous         NaN
15   2018-01-16 08:00:00  2018-01-16 16:00:00    Continuous         NaN
..                   ...                  ...           ...         ...
740  2019-03-04 07:00:00  2019-03-08 18:00:00    Continuous         NaN
741  2019-03-04 08:00:00  2019-04-19 16:00:00    Continuous         NaN
742  2019-03-16 08:00:00  2019-03-16 20:00:00    Continuous         NaN
743  2019-03-18 07:00:00  2019-03-22 18:00:00    Continuous         NaN
744  2019-03-25 07:00:00  2019-03-29 18:00:00    Continuous         NaN

0   Outage Type Path 3 N->S ING - CUS Path 3 N->S BC - US  \
1           NaN                   NaN                 NaN
8           NaN                   NaN                 NaN
9           NaN                   NaN                 NaN
11          NaN                   NaN                 NaN
15          NaN                   NaN                 NaN
..          ...                   ...                 ...
740         NaN                   NaN                 NaN
741         NaN                   NaN                 NaN
742         NaN                   NaN                 NaN
743         NaN                   NaN                 NaN
744         NaN                   NaN                 NaN

0   Path 3 S -> N CUS ING Path 3 S -> N US - BC Path 1 W -> E BC - AB  \
1                     NaN                   NaN                     N
8                     NaN                   NaN                     N
9                     NaN                   NaN                     N
11                    NaN                   NaN                     N
15                    850                   700                     N
..                    ...                   ...                   ...
740                   NaN                   NaN                     N
741                   NaN                   NaN                     N
742                   NaN                   NaN                     N
743                   NaN                   NaN                     N
744                   NaN                   NaN                     N

0   Path 1 E -> W AB - BC             Resource Impact
1                       N  2018-11-14 08:14:56.167000
8                       N  2018-01-08 10:20:41.040000
9                       N  2018-01-08 10:26:28.307000
11                      N  2017-11-21 10:29:23.907000
15                      Y  2017-10-23 10:43:08.120000
..                    ...                         ...
740                     N  2018-10-31 09:31:35.093000
741                     N  2018-03-15 13:38:10.283000
742                     N  2018-02-19 11:33:53.310000
743                     Y  2018-11-21 13:22:23.093000
744                     Y  2018-11-21 13:33:03.077000

[271 rows x 17 columns]

In [ ]:
df= df[~df['Outage Status'].str.contains('|'.join(keywords))]
df['Complete Date']= pd.to_datetime(df['Complete Date'])
df['Start Date']= pd.to_datetime(df['Start Date'])
df['Revision Date']= pd.to_datetime(df['Revision Date'])
df['Start Date'] = df['Start Date'].astype(str)

df['Revision Date'] = df['Revision Date'].astype(str)

# push todays date and filter by flows into Alberta.

df= df[df['Path 1 W -> E BC - AB'] | df['Path 1 E -> W AB - BC'] > 0]
df= df[df['Complete Date'] >= pd.Timestamp.today() - pd.Timedelta('1D')]
df['Complete Date'] = df['Complete Date'].astype(str)